### ISSUE TITLE
Click to Allow Access Link No Longer Functioning

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/gdrive#27]
When clicking on an image to be embedded from the GDrive MEXP functionality, the link to change the permissions on the item is no longer functioning. 

![2019-10-15_18-46-10 (1)](https://user-images.githubusercontent.com/480667/66875496-84880280-ef7c-11e9-8380-a7f8e867bd79.gif)

**Comment by r-a-y** [comment]
@mrjarbenne - I think the change to support Gutenberg may have broken the "Click to allow access" link.  I believe I may have fixed this.  Can you check on production to see if it works for you?

**Comment by mrjarbenne** [comment]
It's working now. Thanks for the quick fix.
