### ISSUE TITLE
Gutenberg updates

### ISSUE THREAD

**Issue by r-a-y** [hwdsb/gdrive#28]
I've noticed some incompatbilities for WordPress 5.3.0 and up.

Will add some fixes for them in this ticket.

**Comment by mrjarbenne** [comment]
Cool. Thanks for looping me in.

**Comment by r-a-y** [comment]
WordPress 5.5.0 changed the look of their blocks again, so I've adapted the look for it. Let me know if you spot any inconsistencies.

**Comment by mrjarbenne** [comment]
Looks great. Did you need to adjust anything for the HWDSB.tv block as well? It looks fine to me, but thought I would check.

**Comment by r-a-y** [comment]
I did the change for the HWDSB.tv block when I made the Google Drive
changes :)
